### ISSUE TITLE
Document `montgomeryAdd` and `montgomerySub`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync_era_precompiles#111]
**Context:** `EcAdd.yul`, `EcMul.yul`, `EcPairing.yul`

**Description:** Function documentations is missing

**Comment by jpcenteno** [comment]
- [ ] EcAdd.yul
- [ ] EcMul.yul
- [ ] ecPairing.yul

**Comment by jpcenteno** [comment]
The docstrings were already there for `EcPairing.yul`.
