### ISSUE TITLE
Implement Big UInt Addition for `modexp`

### ISSUE THREAD

**Issue by IAvecilla** [lambdaclass/zksync_era_precompiles#126]
## Context

`modexp.yul`

## Description

The addition between big integers is needed for the [booth algorithm](https://en.wikipedia.org/wiki/Booth%27s_multiplication_algorithm) implementation

## Recommendation

We'll probably follow this [implementation from Lambdaworks](https://github.com/lambdaclass/lambdaworks/blob/da688cd9f845c1c32216e179dd9389f339117a02/math/src/unsigned_integer/element.rs#L566) repo

**Comment by ilitteri** [comment]
Solved in https://github.com/lambdaclass/zksync_era_precompiles/pull/136
