### ISSUE TITLE
Deploying precompiles on zksync

### ISSUE THREAD

**Issue by zerotwodao** [lambdaclass/zksync_era_precompiles#221]
Hello,

We are currently making a use of zkSNARK Pairing library and would like to use the precompiles prior of deployment to zksync.

https://gist.github.com/chriseth/f9be9d9391efc5beb9704255a8e2989d

@ilitteri Would it be possible to deploy them now?

Thanks.

**Comment by ilitteri** [comment]
Hi! Every precompile that is in main but ModExp is working correctly as precompiles, if you want to deploy them as independent contract you need to add a `return(0, 0)` to their constructor (we're pushing a PR with this fix today though).

**Comment by ilitteri** [comment]
There should not be any troubles, let me know if there's any though. We have an example of deploying one in testnet in #203

**Comment by zerotwodao** [comment]
@ilitteri The static calls and outputs would work exactly as the precompiled ones right?

**Comment by ilitteri** [comment]
Yep, again, let me know if they don't. One thing it take into account (I don't think this would be your case though), if you use our era-test-node, be aware that the output is modified in our favor (the gas used is at the starting of the output).

**Comment by zerotwodao** [comment]
@ilitteri Got this strange error while deploying EcPairing.yul, I have added `return(0, 0)` to the constructor like you told me.

```
  code: 'CALL_EXCEPTION',
  action: 'estimateGas',
  data: null,
  reason: null,
  transaction: {
    to: '0x0000000000000000000000000000000000008006',
    data: '0x9c4d535b00000000000000000000000000000000000000000000000000000000000000000100309f6271bc3cceacd8564e1cd00d5ac78a9294d283b886813bdf14dd200500000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000',
    from: '0xfDbA3B7Db2253cD099A479d11230057389cCBa0D'
  },
  invocation: null,
  revert: null,
  shortMessage: 'missing revert data',
  info: {
    error: {
      code: 3,
      message: 'exceeds limit for published pubdata',
      data: '0x'
    },
    payload: {
      method: 'eth_estimateGas',
      params: [
        {
          type: '0x71',
          nonce: '0x395',
          from: '0xfdba3b7db2253cd099a479d11230057389ccba0d',
          to: '0x0000000000000000000000000000000000008006',
          data: '0x9c4d535b00000000000000000000000000000000000000000000000000000000000000000100309f6271bc3cceacd8564e1cd00d5ac78a9294d283b886813bdf14dd200500000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000',
          eip712Meta: { gasPerPubdata: '0xc350', factoryDeps: [Array] }
        }
      ],
      id: 82,
      jsonrpc: '2.0'
    }
  }
}
```

Using default deployment arguments

```
const {
  ethers,
  zksyncEthers,
} = require('hardhat');
const {
  loadArtifact,
  deployContract,
} = zksyncEthers;

const EcAdd = await deployContract(await loadArtifact('EcAdd'), [], owner);
  await EcAdd.waitForDeployment();

  const EcMul = await deployContract(await loadArtifact('EcMul'), [], owner);
  await EcMul.waitForDeployment();

  const EcPairing = await deployContract(await loadArtifact('EcPairing'), [], owner);
  await EcPairing.waitForDeployment();

  console.log({
    EcAdd: EcAdd.target,
    EcMul: EcMul.target,
    EcPairing: EcPairing.target,
  });
```

Here is the compiled artifact from zkSolc, I have modified from yours

https://gist.github.com/zerotwodao/d24de3d22ca1c779def4a3c01fdf9f52

**Comment by zerotwodao** [comment]
@ilitteri Seems like a compiled bytecode size for EcPairing.yul is too big, would it mean it is impossible to deploy?

**Comment by ilitteri** [comment]
> @ilitteri Seems like a compiled bytecode size for EcPairing.yul is too big.
> 
> Finds out the compiled bytecode for EcPairing exceeds 200kb and the known limit for bytecode size limit is 24kb, would it be impossible to deploy?

Hm, that's bad news. I'm not sure if it'd be possible. Are you trying to deploy on testnet or in a local-net?

**Comment by ilitteri** [comment]
Something that could work (don't know the amount of work it'd involve) is to modularize the precompile (e.g. finite field arithmetics could be part of another library, also the curve arithmetics could be part of another library).

**Comment by zerotwodao** [comment]
@ilitteri Tried to deploy on testnet, and it seems like it is impossible unless we lift off the https://eips.ethereum.org/EIPS/eip-170 size limit, or like you said we could try modularizing the precompile.

**Comment by zerotwodao** [comment]
Do you think it would be possible to request zksync team for the deployment of those precompiles on the different addresses for the testing purpose on mainnet and testnet? It would make our contract work eventually

**Comment by ilitteri** [comment]
Have you tried to compile it with different compilation flags?

**Comment by ilitteri** [comment]
> @ilitteri Which flags are available?

If you run `zksolc --help` you can find this:
```sh
-O, --optimization <optimization> Set the optimization parameter -O[0 | 1 | 2 | 3 | s | z]. Use `3` for best performance and `z` for minimal size
```
In your case I'd use `-Oz` flag.

**Comment by zerotwodao** [comment]
@ilitteri Sorry for late reply I have successfully compiled and deployed the precompiles with ~40kb using the flag `-oZ` ( I don't know why I have used -O3 before ) . After the deployment I have also checked that the precompiles work with the example verifier contract that I have posted the above. Do you know when it will be live on the mainnet?

**Comment by zerotwodao** [comment]
And seems like it is gas costy than the one available from ethereum mainnet would the gas cost for calling function can be decreased if they are deployed as a precompile?

**Comment by ilitteri** [comment]
> @ilitteri Sorry for late reply I have successfully compiled and deployed the precompiles with ~40kb using the flag `-oZ` ( I don't know why I have used -O3 before ) . After the deployment I have also checked that the precompiles work with the example verifier contract that I have posted the above. 

Amazing! Good luck then with your library.

> Do you know when it will be live on the mainnet?

I have no answer for this. The zkSync team is reviewing if it'd be better to have them as circuits instead of as Yul contracts. For the moment, using them as contracts in testnet.

**Comment by ilitteri** [comment]
Closing the issue as it seems to be solved as said [here](https://github.com/lambdaclass/zksync_era_precompiles/issues/221#issuecomment-1930669921).

**Comment by chervyachok** [comment]
> @ilitteri Sorry for late reply I have successfully compiled and deployed the precompiles with ~40kb using the flag `-oZ` ( I don't know why I have used -O3 before ) . After the deployment I have also checked that the precompiles work with the example verifier contract that I have posted the above. Do you know when it will be live on the mainnet?

Could you please share deployment address in zkSync main or testnet

**Comment by zerotwodao** [comment]
@chervyachok Sure

EcAdd: '0xbF3F280F177Befe658A6973E0E57c38d62d1bCc8'

EcMul: '0x8277B56C128e62356306C5a702E1fC2c3dB7192F'

EcPairing: '0x49a31d9776B80450d7E5D514D9a753C99D800E9d'

**Comment by zerotwodao** [comment]
@chervyachok Have you tested with the ethereum testnets for your code? With my case with the gist posted above it works as intended
