### ISSUE TITLE
28/36 Test EcAdd fail

### ISSUE THREAD

**Issue by rdubois-crypto** [lambdaclass/zksync_era_precompiles#223]
Tests are failing when launching the command 
>make test

It seems that some files might be missing to the repo (having tests working locally).

![image](https://github.com/lambdaclass/zksync_era_precompiles/assets/103030189/5bedd908-961f-48a9-a105-f74a43518252)

**Comment by IAvecilla** [comment]
Hey! Have you executed the `era-test-node` with `make run-node` in one terminal and then performed `make test` in another one? If so, please share the errors here to see better what's happening. However, it's expected to fail if the tests can't connect with the local node.

**Comment by rdubois-crypto** [comment]
Hi !

Actually the make run-node is failing. Most likely related to https://github.com/lambdaclass/zksync_era_precompiles/issues/225.

(So fixing it shall very likely solve this one)

**Comment by rdubois-crypto** [comment]
(Thx for the response)

**Comment by rdubois-crypto** [comment]
Those tests are now ok, according to last PR. However ecmul is still failing in some cases.

Closing this issue for a distinct one here:
https://github.com/lambdaclass/zksync_era_precompiles/issues/232
