### ISSUE TITLE
Optimization on `montgomeryAdd`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync_era_precompiles#82]
**Context:** [EcMul.yul#L210](https://github.com/lambdaclass/zksync_era_precompiles/blob/main/precompiles/EcMul.yul#L210)

**Description:**

Update `montgomeryAdd` implementation for a more efficient one.

**Recommendation:**

```solidity
function montgomeryAdd(augend, addend) -> ret {
    ret := add(augend, addend)
    if gt(ret, P()) {
        ret := sub(ret, P())
    }
}
```

This will be more efficient since `addmod` cares about overflow, but it couldn't happen in our case (253 bits long numbers)

**Comment by IAvecilla** [comment]
I think the context should add `ecAdd` and `ecPairing` since we also got montgomery there
